name: Build & Publish Android Artifacts

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type (release/debug)'
        required: true
        default: 'debug' # Nilai default dapat disesuaikan

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      buildType: ${{ github.event.inputs.build-type }}
    steps:
    - name: Check
      uses: actions/checkout@v3.5.2
    - name: Setup JDK 11
      uses: actions/setup-java@v1.4.4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2
      with:
        gradle-version: 8.1.1
        arguments: :android:build -P${{ env.buildType }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: buildAPK
        path: ${{ github.workspace }}/android/build/outputs/apk/${{ env.buildType }}/android-${{ env.buildType }}.apk
