name: Gradle Auto

on:
  workflow_dispatch:
    inputs:
      formating:
        default: false
        required: false
        type: boolean
      platform_type:
        default: 'android'
        required: true
        options:
          - android
          - desktop
        type: choice
      build_type:
        default: 'debug'
        required: true
        options:
          - debug
          - release
        type: choice

jobs:
  format:
    if: ${{ inputs.formating }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Format Code C++
        run: |
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp"
          sudo apt-get install -y clang-format
          find . -name "*.cpp" -o -name "*.hpp" | xargs clang-format -i
          git add .
          git commit -m "Reformatting cpp"
          git push
      - name: Setup JDK 11
        if: ${{ inputs.platform_type == 'android' }}
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Format Java Code
        if: ${{ inputs.platform_type == 'android' }}
        uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          files: "android/src/**/*.java"
          args: "-r -a"

  build-android:
    runs-on: ubuntu-latest
    if: ${{ inputs.platform_type == 'android' }}
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Build Android APK
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 8.1.1
          arguments: :android:build -P${{ inputs.build_type }}
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: android-${{ inputs.build_type }}
          path: ${{ github.workspace }}/android/build/outputs/apk/${{ inputs.build_type }}/android-${{ inputs.build_type }}.apk

  build-desktop:
    if: ${{ inputs.platform_type == 'desktop' }}
    strategy:
      matrix:
        config:
          - {
            name: "Windows_X86",
            os: windows-latest,
            args: -G "Visual Studio 16 2019" -A Win32,
          }
          - {
            name: "Windows_X64",
            os: windows-latest,
            args: -G "Visual Studio 16 2019" -A x64,
          }
          - {
            name: "Ubuntu_X64",
            os: ubuntu-latest,
            args: "",
          }
          - {
            name: "MacOSX_X64",
            os: macos-latest,
            args: "",
          }
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up MSVC
        if: matrix.config.os == 'windows-latest'
        uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x64
      - name: File Work
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          cd desktop/main/
          mkdir build
          cd build
          cmake .. ${{ matrix.config.args }} -DCMAKE_BUILD_TYPE=${{ inputs.platform_type }}
          cmake --build . -j --config ${{ inputs.platform_type }}
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: desktop-${{ matrix.config.name }}-${{ inputs.build_type }}
          path: ${{ github.workspace }}/desktop/main/build


