name: Auto-Check

on:
  push:
    paths:
      - 'core/**'
      - 'android/**'
      - 'desktop/**'
      - 'tools/**'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        submodule: [core, android, desktop, tools]
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Filter Changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          base: ${{ github.ref }}
          filters: |
            i:
              - '${{ matrix.submodule }}/**'
      - name: Gradle Check
        if: steps.changes.outputs.i == 'true'
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 8.4
          arguments: :${{ matrix.submodule }}:check