name: Gradle Auto

on:
  workflow_dispatch:
    inputs:
      format_java:
        default: false
        required: false
        type: boolean
      format_cpp:
        default: false
        required: false
        type: boolean
      platform_type:
        default: 'android'
        required: true
        options:
          - android
          - desktop
        type: choice
      build_type:
        default: 'debug'
        required: true
        options:
          - debug
          - release
        type: choice

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check
      uses: actions/checkout@v3.5.2
    - name: Setup JDK 11
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Java Format
      if:  ${{ inputs.format_java }} && ${{ inputs.platform_type == 'android' }} 
      uses: axel-op/googlejavaformat-action@v3.6.0
      with:
        files: "android/src/**/*.java"
        args: "-r -a"
    - name: Global Cpp Format
      if:  ${{ inputs.format_cpp }}
      run: |
        git config --global user.email "ikomangwidiadaariasa12@gmail.com"
        git config --global user.name "AriasaProp"
        sudo apt-get install -y clang-format
        find . -name "*.cpp" -o -name "*.hpp" | xargs clang-format -i
        git add .
        git commit -m "reformating cpp"
        git push
    - name: Gradle Build ${{ inputs.platform_type }} - ${{ inputs.build_type }}
      uses: gradle/gradle-build-action@v2.4.2
      with:
        gradle-version: 8.1.1
        arguments: :${{ inputs.platform_type }}:build -P${{ inputs.build_type }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ inputs.platform_type }}-${{ inputs.build_type }}
        path: ${{ github.workspace }}/android/build/outputs/apk/${{ inputs.build_type }}/android-${{ inputs.build_type }}.apk

