name: Auto-Check

on:
  push:
    paths:
      - 'core/**'
      - 'android/**'
      - 'desktop/**'
      - 'tools/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Filter Changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          base: ${{ github.ref }}
          filters: |
            tools:
              - 'tools/**'
            core:
              - 'core/**'
            android:
              - 'core/**'
              - 'android/**'
            desktop:
              - 'core/**'
              - 'desktop/**'
      - name: Gradle Check Tools
        if: steps.changes.outputs.tools
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 8.4
          arguments: :tools:tries
      - name: Gradle Check Core
        if: steps.changes.outputs.core
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 8.4
          arguments: :core:check
      - name: Gradle Check Android
        if: steps.changes.outputs.android
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 8.4
          arguments: :android:check
      - name: Gradle Check Desktop
        if: steps.changes.outputs.desktop
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 8.4
          arguments: :desktop:check