name: Build and Run C++ Program

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - run: sudo apt-get install -y build-essential cmake
    - name: Try executable
      run: |
        cd tools/main
        mkdir build
        cd build
        cmake ..
        make
        ./Converter
    - uses: actions/upload-artifact@v3.1.2
      with:
        name: Converter
        path: ${{ github.workspace }}/tools/main/build/Converter
