name: Build and Run C++ Program

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - run: sudo apt-get install -y build-essential cmake
    - name: Try executable
      run: |
        cd tools/build
        cmake ../main
        make
        ./Converter
        ./Converter -i test.jpeg -o out.jpeg
    - uses: actions/upload-artifact@v3.1.2
      with:
        name: Image-Samples
        path: ${{ github.workspace }}/tools/main/build/out.jpeg
