name: Clean Workflows

on: [workflow_dispatch]

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Delete workflow runs
        run: |
          run_ids=$(gh api repos/${{ github.repository }}/actions/runs --jq '.workflow_runs[] | select(.status != "in_progress") | .id');
          for run_id in $run_ids; do
              gh api repos/${{ github.repository }}/actions/runs/$run_id --method DELETE;
          done;
          artifact_ids=$(gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[]  | .id');
          for artifact_id in $artifact_ids; do
              gh api repos/${{ github.repository }}/actions/artifact/$artifact_id --method DELETE;
          done;
          
