name: Core Auto Update

on:
  push:
    paths:
      - 'core/**'
      - 'android/**'
      - 'desktop/**'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.changes.outputs.core }}
      android: ${{ steps.changes.outputs.android }}
      desktop: ${{ steps.changes.outputs.desktop }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Check for changes
        id: changes
        uses: dorny/paths-filter@v3.0.1
        with:
          filters: |
            core:
              - 'core/**'
              - 'android/**'
              - 'desktop/**'
            android:
              - 'android/**'
            desktop:
              - 'desktop/**'

  core:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.core == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Check Changes
        uses: dorny/paths-filter@v3.0.1
        id: changes
        with:
          list-files: shell
          filters: |
            core-src:
              - added|modified: 'core/**/*.cpp'
              - added|modified: 'core/**/*.hpp'

      - name: Format Code C++
        if: ${{ steps.changes.outputs.core-src == 'true' }}
        run: |
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp"
          sudo apt-get install -y clang-format
          echo ${{ steps.changes.outputs.core-src_files }} | xargs -n 1 clang-format -i
          git add .
          git commit -m "Core Reformatting Sources"

      - name: Publish in github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Gradle Check Core
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Run Check
        run: gradle :core:check 

  android:
    runs-on: ubuntu-latest
    needs: [check-changes, core]
    if: |
      needs.check-changes.outputs.android == 'true' &&
      (needs.core.result == 'success' || needs.core.result == 'skipped')
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Check Changes
        uses: dorny/paths-filter@v3.0.1
        id: changes
        with:
          filters: |
            android-java:
              - added|modified: 'android/src/**/*.java'

      - name: Format Java Code
        if: ${{ steps.changes.outputs.android-java == 'true' }}
        uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          files: "android/src/**/*.java"
          args: "-r -a"

      - name: Gradle Build Android
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Run Build Release
        run: gradle :android:build -Prelease

      - name: Upload Android APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: APK
          path: ${{ github.workspace }}/android/build/outputs/apk/release/android-release.apk 

  desktop:
    runs-on: ubuntu-latest
    needs: [check-changes, core]
    if: |
      needs.check-changes.outputs.desktop == 'true' &&
      (needs.core.result == 'success' || needs.core.result == 'skipped')
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Check Changes
        uses: dorny/paths-filter@v3.0.1
        id: changes
        with:
          list-files: shell
          filters: |
            desktop-src:
              - added|modified: 'desktop/**/*.cpp'
              - added|modified: 'desktop/**/*.hpp'

      - name: Format Code C++
        if: ${{ steps.changes.outputs.core-src == 'true' }}
        run: |
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp"
          sudo apt-get install -y clang-format
          echo ${{ steps.changes.outputs.desktop-src_files }} | xargs -n 1 clang-format -i
          git add .
          git commit -m "Core Reformatting Sources"

      - name: Publish in github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle Build Desktop
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Run Build
        run: gradle :desktop:build

      - name: Upload Desktop EXE
        uses: actions/upload-artifact@v4.3.3
        with:
          name: EXE
          path: ${{ github.workspace }}/desktop/build 
