name: Core Auto Update

on:
  push:
    paths:
      - 'core/**'
      - 'android/**'
      - 'desktop/**'
      - 'tools/**'

jobs:
  format-core:
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.changes.outputs.android }}
      desktop: ${{ steps.changes.outputs.desktop }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Check for changes
        id: changes
        uses: dorny/paths-filter@v3.0.1
        with:
          list-files: shell
          filters: |
            core:
              - 'core/**'
            android:
              - 'android/**'
            desktop:
              - 'desktop/**'
            tools:
              - 'tools/**'
            cpp-src:
              - added|modified: 'core/**/*.cpp'
              - added|modified: 'core/**/*.hpp'
              - added|modified: 'tools/**/*.cpp'
              - added|modified: 'tools/**/*.hpp'
              - added|modified: 'desktop/**/*.cpp'
              - added|modified: 'desktop/**/*.hpp'
              - added|modified: 'android/src/main/cpp/**/*.cpp'
              - added|modified: 'android/src/main/cpp/**/*.hpp'
            java-src:
              - 'android/src/main/java/**/*.java'

      - uses: axel-op/googlejavaformat-action@v3.6.0
        if: steps.changes.outputs.java-src == 'true'
        continue-on-error: true
        with:
          files: "android/src/**/*.java"
          args: "-r -a"
          skipCommit: false

      - name: Format Code C++
        if: steps.changes.outputs.cpp-src == 'true'
        run: |
          sudo apt-get install -y clang-format
          echo ${{ steps.changes.outputs.cpp-src_files }} | xargs -n 1 clang-format -i
 
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
 
      - uses: gradle/actions/setup-gradle@v3
 
      - run: gradle :core:test
        if: steps.changes.outputs.core == 'true'

      - run: gradle :tools:test
        #if: steps.changes.outputs.tools == 'true'

      - name: Push changes
        continue-on-error: true
        if: always()
        run: |
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp"
          git add .
          git commit -m "Reformatting Code Sources"
          git push

  android:
    runs-on: ubuntu-latest
    needs: format-core
    if: needs.format-core.outputs.android == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
 
      - uses: gradle/actions/setup-gradle@v3
      - run: gradle :android:build -Prelease

      - name: Upload Android APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: APK
          path: ${{ github.workspace }}/android/build/outputs/apk/release/android-release.apk 

  desktop:
    runs-on: ubuntu-latest
    needs: format-core
    if: needs.format-core.outputs.desktop == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - uses: gradle/actions/setup-gradle@v3
      - run: gradle :desktop:build

      - name: Upload Desktop EXE
        uses: actions/upload-artifact@v4.3.3
        with:
          name: EXE
          path: ${{ github.workspace }}/desktop/build 
