name: Formatting

on: [workflow_dispatch]

permissions:
  actions: write
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Format Java Code
        uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          files: "android/src/**/*.java"
          args: "-r -a"

      - name: Format Code C++
        run: |
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp"
          sudo apt-get install -y clang-format
          find . -name "tools/**/*.cpp" -o -name "tools/**/*.hpp" | xargs clang-format -i
          find . -name "core/**/*.cpp" -o -name "core/**/*.hpp" | xargs clang-format -i
          find . -name "android/src/main/**/*.cpp" -o -name "android/src/main/**/*.hpp" | xargs clang-format -i
          find . -name "desktop/**/*.cpp" -o -name "desktop/**/*.hpp" | xargs clang-format -i
          git add .
          git commit -m "Reformatting cpp"

      - name: Publish in github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

