name: Formating Clang Code

on:
  push:
    paths:
      - 'cpp-formatting.txt'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - run: |
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp"
          sudo apt-get install -y clang-format
          clang-format -i **/*.cpp **/*.hpp
          clang-format core/assets/bmfont.cpp
          clang-format core/assets/bmfont.hpp
          git add .
          git commit -m "reformating cpp"
          git push
