name: Upgrade

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
          cd android
          gradle wrapper --gradle-version release-candidate
          cd ..
      - run: |
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp"
          git add .
          if (git commit -m "Upgrade"); then
          	git push
          fi